export const POSTAL_CODES_REQUESTED = 'POSTAL_CODES_REQUESTED';
export const POSTAL_CODES_RECEIVED = 'POSTAL_CODES_RECEIVED';

export const LISTINGS_REQUESTED = 'LISTINGS_REQUESTED';
export const LISTINGS_RECEIVED = 'LISTINGS_RECEIVED';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';